### ISSUE TITLE
Input could not be parsed (probably it is not valid MathML)

### ISSUE THREAD

**Issue by wildanm** [MIR-MU/MIaS#3]
Dear All, 

I'm trying to index MathML using MIaS, but the parser, always raise an error, following is the content of the test file i want to index. Am i missing something here ?

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
<mrow>
  <mrow>
    <msup>
      <mi>x</mi>
      <mn>2</mn>
    </msup>
    <mo>+</mo>
    <mrow>
      <mn>4</mn>
      <mo>⁢</mo>
      <mi>x</mi>
    </mrow>
    <mo>+</mo>
    <mn>4</mn>
  </mrow>
  <mo>=</mo>
  <mn>0</mn>
</mrow>
</math>
```

```
2017-05-14 17:11:25,795 [main] INFO  cz.muni.fi.mias.indexing.Indexing - adding to index tes2/quadratic_equation.html docId=tes2/quadratic_equation.html#0
2017-05-14 17:11:26,137 [main] WARN  cz.muni.fi.mias.math.MathTokenizer - Input could not be parsed (probably it is not valid MathML)
cz.muni.fi.mir.mathmlcanonicalization.modules.ModuleException: Error while parsing the input file
	at cz.muni.fi.mir.mathmlcanonicalization.modules.ElementMinimizer.execute(ElementMinimizer.java:86) ~[mathml-canonicalizer-1.3.1.jar:?]
	at cz.muni.fi.mir.mathmlcanonicalization.MathMLCanonicalizer.executeStreamModules(MathMLCanonicalizer.java:368) ~[mathml-canonicalizer-1.3.1.jar:?]
	at cz.muni.fi.mir.mathmlcanonicalization.MathMLCanonicalizer.canonicalize(MathMLCanonicalizer.java:330) ~[mathml-canonicalizer-1.3.1.jar:?]
	at cz.muni.fi.mias.math.MathTokenizer.parseMathML(MathTokenizer.java:302) [miasmath-1.6.6-4.10.4-SNAPSHOT.jar:?]
	at cz.muni.fi.mias.math.MathTokenizer.processFormulae(MathTokenizer.java:278) [miasmath-1.6.6-4.10.4-SNAPSHOT.jar:?]
	at cz.muni.fi.mias.math.MathTokenizer.reset(MathTokenizer.java:244) [miasmath-1.6.6-4.10.4-SNAPSHOT.jar:?]
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:613) [lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:359) [lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:318) [lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:241) [lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:465) [lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1526) [lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1500) [lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at cz.muni.fi.mias.indexing.Indexing.indexDocsThreaded(Indexing.java:145) [MIaS-1.6.6-4.10.4-SNAPSHOT.jar:?]
	at cz.muni.fi.mias.indexing.Indexing.indexFiles(Indexing.java:89) [MIaS-1.6.6-4.10.4-SNAPSHOT.jar:?]
	at cz.muni.fi.mias.MIaS.main(MIaS.java:34) [MIaS-1.6.6-4.10.4-SNAPSHOT.jar:?]
Caused by: com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedEOF(StreamScanner.java:686) ~[wstx-asl-3.2.7.jar:3.2.7]
	at com.ctc.wstx.sr.BasicStreamReader.handleEOF(BasicStreamReader.java:2134) ~[wstx-asl-3.2.7.jar:3.2.7]
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2040) ~[wstx-asl-3.2.7.jar:3.2.7]
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1069) ~[wstx-asl-3.2.7.jar:3.2.7]
	at cz.muni.fi.mir.mathmlcanonicalization.modules.ElementMinimizer.minimizeElements(ElementMinimizer.java:133) ~[mathml-canonicalizer-1.3.1.jar:?]
	at cz.muni.fi.mir.mathmlcanonicalization.modules.ElementMinimizer.execute(ElementMinimizer.java:82) ~[mathml-canonicalizer-1.3.1.jar:?]
	... 15 more
```

**Comment by michal-ruzicka** [comment]
I am very sorry but I was unable to reproduce the error with the input file
```bash
$ cat file.html 
<math xmlns="http://www.w3.org/1998/Math/MathML">
<mrow>
  <mrow>
    <msup>
      <mi>x</mi>
      <mn>2</mn>
    </msup>
    <mo>+</mo>
    <mrow>
      <mn>4</mn>
      <mo>⁢</mo>
      <mi>x</mi>
    </mrow>
    <mo>+</mo>
    <mn>4</mn>
  </mrow>
  <mo>=</mo>
  <mn>0</mn>
</mrow>
</math>
```

**Comment by fras2560** [comment]
I was able to reproduce the error. 

Jul 11, 2017 1:24:10 PM cz.muni.fi.mir.mathmlcanonicalization.modules.ElementMinimizer execute
SEVERE: error while parsing the input file. 
com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedEOF(StreamScanner.java:686)
	at com.ctc.wstx.sr.BasicStreamReader.handleEOF(BasicStreamReader.java:2134)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2040)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1069)
	at cz.muni.fi.mir.mathmlcanonicalization.modules.ElementMinimizer.minimizeElements(ElementMinimizer.java:133)
	at cz.muni.fi.mir.mathmlcanonicalization.modules.ElementMinimizer.execute(ElementMinimizer.java:82)
	at cz.muni.fi.mir.mathmlcanonicalization.MathMLCanonicalizer.executeStreamModules(MathMLCanonicalizer.java:364)
	at cz.muni.fi.mir.mathmlcanonicalization.MathMLCanonicalizer.canonicalize(MathMLCanonicalizer.java:327)
	at cz.muni.fi.mias.math.MathTokenizer.parseMathML(MathTokenizer.java:302)
	at cz.muni.fi.mias.math.MathTokenizer.processFormulae(MathTokenizer.java:278)
	at cz.muni.fi.mias.math.MathTokenizer.reset(MathTokenizer.java:244)
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:613)
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:359)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:318)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:241)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:465)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1526)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1500)
	at cz.muni.fi.mias.indexing.Indexing.indexDocsThreaded(Indexing.java:145)
	at cz.muni.fi.mias.indexing.Indexing.indexFiles(Indexing.java:89)
	at cz.muni.fi.mias.MIaS.main(MIaS.java:34)

2017-07-11 13:24:10,301 [main] WARN  cz.muni.fi.mias.math.MathTokenizer - Input could not be parsed (probably it is not valid MathML)
cz.muni.fi.mir.mathmlcanonicalization.modules.ModuleException: Error while parsing the input file
	at cz.muni.fi.mir.mathmlcanonicalization.modules.ElementMinimizer.execute(ElementMinimizer.java:86) ~[mathml-canonicalizer-1.4.0-SNAPSHOT.jar:?]
	at cz.muni.fi.mir.mathmlcanonicalization.MathMLCanonicalizer.executeStreamModules(MathMLCanonicalizer.java:364) ~[mathml-canonicalizer-1.4.0-SNAPSHOT.jar:?]
	at cz.muni.fi.mir.mathmlcanonicalization.MathMLCanonicalizer.canonicalize(MathMLCanonicalizer.java:327) ~[mathml-canonicalizer-1.4.0-SNAPSHOT.jar:?]
	at cz.muni.fi.mias.math.MathTokenizer.parseMathML(MathTokenizer.java:302) [miasmath-1.6.6-4.10.4-SNAPSHOT.jar:?]
	at cz.muni.fi.mias.math.MathTokenizer.processFormulae(MathTokenizer.java:278) [miasmath-1.6.6-4.10.4-SNAPSHOT.jar:?]
	at cz.muni.fi.mias.math.MathTokenizer.reset(MathTokenizer.java:244) [miasmath-1.6.6-4.10.4-SNAPSHOT.jar:?]
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:613) [lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:359) [lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:318) [lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:241) [lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:465) [lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1526) [lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1500) [lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at cz.muni.fi.mias.indexing.Indexing.indexDocsThreaded(Indexing.java:145) [MIaS-1.6.6-4.10.4-SNAPSHOT.jar:?]
	at cz.muni.fi.mias.indexing.Indexing.indexFiles(Indexing.java:89) [MIaS-1.6.6-4.10.4-SNAPSHOT.jar:?]
	at cz.muni.fi.mias.MIaS.main(MIaS.java:34) [MIaS-1.6.6-4.10.4-SNAPSHOT.jar:?]
Caused by: com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedEOF(StreamScanner.java:686) ~[wstx-asl-3.2.7.jar:3.2.7]
	at com.ctc.wstx.sr.BasicStreamReader.handleEOF(BasicStreamReader.java:2134) ~[wstx-asl-3.2.7.jar:3.2.7]
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2040) ~[wstx-asl-3.2.7.jar:3.2.7]
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1069) ~[wstx-asl-3.2.7.jar:3.2.7]
	at cz.muni.fi.mir.mathmlcanonicalization.modules.ElementMinimizer.minimizeElements(ElementMinimizer.java:133) ~[mathml-canonicalizer-1.4.0-SNAPSHOT.jar:?]
	at cz.muni.fi.mir.mathmlcanonicalization.modules.ElementMinimizer.execute(ElementMinimizer.java:82) ~[mathml-canonicalizer-1.4.0-SNAPSHOT.jar:?]
	... 15 more

**Comment by michal-ruzicka** [comment]
Please, what was the exact version of components (Git commit id, preferably) and command line used?

**Comment by fras2560** [comment]
MathMLCan - 06d81cd43dbde75a7c9980b2cf90e5e9e4e07eba
MathMLUnificator - c150445f97c307714c21513a5b29d082d9a5973a
MIaSMath - f33f83be03e6802e322299d7cc34b5522a5e616c
MIaS -  1189259c3cc344a01ad0ef4b070d8390bc8306c8
WebMIaS - 2f6c6624df0cca1c4d3dbc4e172b5858eeac56b2

Ubuntu Terminal - running the following command - 
d6fraser@scspc658:~/Documents/Research/MIaS/MIaS/target$ java -jar MIaS-1.6.6-4.10.4-SNAPSHOT.jar -conf /home/d6fraser/Documents/Research/MIaS/MIaS/conf/mias.properties -add /home/d6fraser/Documents/Research/MIaS/MIaS/data/test/ /home/d6fraser/Documents/Research/MIaS/MIaS/data/tindex/

Here is what the file looks like:
```
$ cat test.html 
<math xmlns="http://www.w3.org/1998/Math/MathML">
<mrow>
  <mrow>
    <msup>
      <mi>x</mi>
      <mn>2</mn>
    </msup>
    <mo>+</mo>
    <mrow>
      <mn>4</mn>
      <mo>⁢</mo>
      <mi>x</mi>
    </mrow>
    <mo>+</mo>
    <mn>4</mn>
  </mrow>
  <mo>=</mo>
  <mn>0</mn>
</mrow>

```

**Comment by michal-ruzicka** [comment]
I am very sorry, it seems to be very strange now, but using the exactly the same versions of the components and command line I am still unable to reproduce the error:

```bash
$ cat  mias-test.sh 
#!/bin/bash

indexdir="index"
datadir="data"

pushd ~/zzz/MathMLCan
    git rev-parse --verify HEAD
    mvn clean install || exit 1
popd
 
pushd ~/zzz/MathMLUnificator
    git rev-parse --verify HEAD
    mvn clean install || exit 2
popd
 
pushd ~/zzz/MIaSMath
    git rev-parse --verify HEAD
    mvn clean install || exit 3
popd

pushd ~/zzz/MIaS
    git rev-parse --verify HEAD
    mvn clean install || exit 4
popd

pushd ~/zzz/WebMIaS
    git rev-parse --verify HEAD
    mvn clean install || exit 5
popd

rm -rv ~/sandbox/zzz-mias-test/{lib,MIaS-ZZZ-TEST.jar,nohup.out} #|| exit 6
cp -via ~/zzz/MIaS/target/{lib,MIaS-ZZZ-TEST.jar} ~/sandbox/zzz-mias-test || exit 7

pushd ~/sandbox/zzz-mias-test/
cat > mias.properties <<EOT
INDEXDIR=/home/ruzicka/sandbox/zzz-mias-test/${indexdir}
UPDATE=false
THREADS=16
MAXRESULTS=10000
DOCLIMIT=-1
FORMULA_DOCUMENTS=false
EOT
    #java -jar MIaS-ZZZ-TEST.jar -conf mias.properties -overwrite ~/sandbox/zzz-mias-test/"${datadir}"/ ~/sandbox/zzz-mias-test/"${datadir}"/ |& tee nohup.out
    java -jar MIaS-ZZZ-TEST.jar -conf mias.properties -add ~/sandbox/zzz-mias-test/"${datadir}"/ ~/sandbox/zzz-mias-test/"${datadir}"/ |& tee nohup.out
popd
```

```xml
$ cat data/test.html 
<math xmlns="http://www.w3.org/1998/Math/MathML">
<mrow>
  <mrow>
    <msup>
      <mi>x</mi>
      <mn>2</mn>
    </msup>
    <mo>+</mo>
    <mrow>
      <mn>4</mn>
      <mo>⁢</mo>
      <mi>x</mi>
    </mrow>
    <mo>+</mo>
    <mn>4</mn>
  </mrow>
  <mo>=</mo>
  <mn>0</mn>
</mrow>
</math>
```

```bash
$ ./mias-test.sh
...
2017-07-14 09:58:08,437 [main] INFO  cz.muni.fi.mias.indexing.Indexing - Getting list of documents to index.
2017-07-14 09:58:08,441 [main] INFO  cz.muni.fi.mias.indexing.Indexing - Number of documents to index is 1
2017-07-14 09:58:08,588 [main] INFO  cz.muni.fi.mias.indexing.Indexing - ---------------------------------
2017-07-14 09:58:08,589 [main] INFO  cz.muni.fi.mias.indexing.Indexing - 
2017-07-14 09:58:08,589 [main] INFO  cz.muni.fi.mias.indexing.Indexing - 0 DONE in total time 235 ms
2017-07-14 09:58:08,589 [main] INFO  cz.muni.fi.mias.indexing.Indexing - CPU time 722 ms
2017-07-14 09:58:08,589 [main] INFO  cz.muni.fi.mias.indexing.Indexing - user time 660 ms
2017-07-14 09:58:08,589 [main] INFO  cz.muni.fi.mias.math.MathTokenizer - Input formulae: 0
2017-07-14 09:58:08,589 [main] INFO  cz.muni.fi.mias.math.MathTokenizer - Indexed formulae: 0
2017-07-14 09:58:08,589 [main] INFO  cz.muni.fi.mias.indexing.Indexing - 
2017-07-14 09:58:08,590 [main] INFO  cz.muni.fi.mias.indexing.Indexing - adding to index est.html docId=est.html
2017-07-14 09:58:08,689 [main] INFO  cz.muni.fi.mias.indexing.Indexing - Documents indexed: 1
2017-07-14 09:58:08,689 [main] INFO  cz.muni.fi.mias.indexing.Indexing - File progress: 1 of 1 done...
2017-07-14 09:58:08,689 [main] INFO  cz.muni.fi.mias.indexing.Indexing - ---------------------------------
2017-07-14 09:58:08,689 [main] INFO  cz.muni.fi.mias.indexing.Indexing - 
2017-07-14 09:58:08,689 [main] INFO  cz.muni.fi.mias.indexing.Indexing - 1 DONE in total time 335 ms
2017-07-14 09:58:08,689 [main] INFO  cz.muni.fi.mias.indexing.Indexing - CPU time 818 ms
2017-07-14 09:58:08,690 [main] INFO  cz.muni.fi.mias.indexing.Indexing - user time 750 ms
2017-07-14 09:58:08,690 [main] INFO  cz.muni.fi.mias.math.MathTokenizer - Input formulae: 2
2017-07-14 09:58:08,690 [main] INFO  cz.muni.fi.mias.math.MathTokenizer - Indexed formulae: 20
2017-07-14 09:58:08,690 [main] INFO  cz.muni.fi.mias.indexing.Indexing - 
~/sandbox/zzz-mias-test
```

Please, what is the contents of yours `mias.properties` config file?

Beware the version of the component (dependencies) to be used is given by the artefact version in `pom.xml` of each of the components. For testing it could be useful to set our own version of the five MIaS tools (I have used `ZZZ-TEST` above) to be sure you are really using your locally build JARs from your sources and not pre-build version downloaded via Maven from world-wide repository. Also be aware of caching of once build version via Maven. Using completely new (never before used) version ID could be useful to be sure you are  really using the version of components you think you are using.

**Comment by fras2560** [comment]
Using your testing script I was able to index the test file.
