### ISSUE TITLE
Trying to Index

### ISSUE THREAD

**Issue by fras2560** [MIR-MU/MIaS#4]
I am trying to index and I believe I correctly installed all the different components with maven. When I run the following command: java -jar MIaS-1.6.6-4.10.4-SNAPSHOT-jar-with-dependencies.jar -conf /home/d6fraser/Documents/Research/MIaS/MIaS/conf/mias.properties -add /home/d6fraser/Documents/Research/MIaS/MIaS/data/doc/ /home/d6fraser/Documents/Research/MIaS/MIaS/data/index/

I get the following error:
xception in thread "main" java.util.ServiceConfigurationError: Cannot instantiate SPI class: org.apache.lucene.codecs.appending.AppendingCodec
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:77)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:47)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:37)
	at org.apache.lucene.codecs.Codec.<clinit>(Codec.java:41)
	at org.apache.lucene.index.LiveIndexWriterConfig.<init>(LiveIndexWriterConfig.java:125)
	at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:171)
	at cz.muni.fi.mias.indexing.Indexing.indexFiles(Indexing.java:78)
	at cz.muni.fi.mias.MIaS.main(MIaS.java:34)
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene40' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [OrdsLucene41, BloomFilter, Direct, FSTOrd41, FSTOrdPulsing41, FST41, FSTPulsing41, Memory, Pulsing41, SimpleText]
	at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:109)
	at org.apache.lucene.codecs.PostingsFormat.forName(PostingsFormat.java:100)
	at org.apache.lucene.codecs.lucene40.Lucene40Codec.<init>(Lucene40Codec.java:117)
	at org.apache.lucene.codecs.appending.AppendingCodec.<init>(AppendingCodec.java:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:67)
	... 7 more

Just not exactly sure why it is not finding the correct codec. Should I be running a different command?

**Comment by michal-ruzicka** [comment]
Dear @fras2560, it is possible there is some problem with the `...-jar-with-dependencies.jar` bundle. Please, try the command with `MIaS-1.6.6-4.10.4-SNAPSHOT.jar` JAR having the `lib/` subdirectory as prepared by the IDE in the `target/` subdirectory.

**Comment by fras2560** [comment]
That worked for me.
